version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=orangehrm
      - MARIADB_DATABASE=orangehrm
      # - MARIADB_PASSWORD=admin123
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  orangehrm:
    image: docker.io/bitnami/orangehrm:4
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_PORT_NUMBER=3306
      - ORANGEHRM_DATABASE_USER=orangehrm
      - ORANGEHRM_DATABASE_NAME=orangehrm
      - ORANGEHRM_DATABASE_PASSWORD=admin123
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - ORANGEHRM_USERNAME=admin
      - ORANGEHRM_PASSWORD=Bitnami.12345
    volumes:
      - 'orangehrm_data:/bitnami/orangehrm'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  orangehrm_data:
    driver: local
